### ISSUE TITLE
Modify controller activity report to support new GCAP policy guidelines

### ISSUE THREAD

**Issue by FriedrichKayak** [vZMA/web-api#1]
Request to modify the current API service for controller activity to be more generic, accept parameters, and therefore support new controller activity requirements of GCAP. 

Ideally, the API call should accept a start date and end date, and report controller activity that occurs between those two dates, _inclusive_ of the start and end date.

Example, 10/1/2023 to 12/31/2023 would include controlling activity any time after midnight on 10/1/2023 up to including 23:59:59 on 12/31/2023.

**Comment by tomcoombs2000** [comment]
Completed.
